#
# Executes commands at login pre-zshrc.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

#
# Browser
#

if [[ "$OSTYPE" == darwin* ]]; then
  export BROWSER='open'
fi

#
# Editors
#

alias e='emacsclient -q -a emacs'
EDITOR=emacsclient
export ALTERNATE_EDITOR=

#function e {
#    tmux new-window -a -n "emacs" "$EDITOR $@"
#}

#function ee {
#    tmux split-window "$EDITOR $@"
#}


export GIT_EDITOR=$EDITOR
export VISUAL=$EDITOR
alias ec=$EDITOR

#
# Language
#

if [[ -z "$LANG" ]]; then
  export LANG='en_US.UTF-8'
fi

#
# Paths
#

# Ensure path arrays do not contain duplicates.
export LD_LIBRARY_PATH=$HOME/lib:$HOME/.local/lib
typeset -T LD_LIBRARY_PATH ld_library_path
typeset -U ld_libraray_path cdpath fpath mailpath manpath infopath path

# Set the list of directories that cd searches.
cdpath=(
     $cdpath
)

# Set the list of directories that Zsh searches for programs.
path=(
  $HOME/{bin,sbin}
  /usr/local/{bin,sbin}
  /usr/{bin,sbin}
  /{bin,sbin}
  $path
)

# Function path
fpath=(
  $HOME/bin
  /usr/local/bin
  $fpath
)

# Man path
manpath=(
  $HOME/man
  $HOME/share/man
  /usr/local/share/man
  /usr/local/man
  $manpath
)

# Info path
infopath=(
  $HOME/share/info
  /usr/local/share/info
  /usr/share/info
  $infopath
)

#
# persistent ssh session with tmux
#
function rtmux {
  case "$2" in
    "") autossh -M 0 $1 -t "zsh -c 'if tmux -qu has; then tmux -qu attach; else EDITOR=vim tmux -qu new; fi'";;
    *) autossh -M 0 $1 -t "zsh -c 'if tmux -qu has -t $2; then tmux -qu attach -t $2; else EDITOR=vim tmux -qu new -s $2; fi'";;
  esac
}

# split window in two and run command
function tmw {
    tmux split-window -dh "$*"
}

#
# tmuxinator
#
if [ -f $HOME/.bin/tmuxinator.zsh ] ; then
   source $HOME/.bin/tmuxinator.zsh
fi

#
# Less
#

# Set the default Less options.
# Mouse-wheel scrolling has been disabled by -X (disable screen clearing).
# Remove -X and -F (exit if the content fits on one screen) to enable it.
#export LESS='-F -g -i -M -R -S -w -X -z-4'
#export LSCOLORS="exfxcxdxbxegedabagacad"

# Set the Less input preprocessor.
# Try both `lesspipe` and `lesspipe.sh` as either might exist on a system.
#if (( $#commands[(i)lesspipe(|.sh)] )); then
#  export LESSOPEN="| /usr/bin/env $commands[(i)lesspipe(|.sh)] %s 2>&-"
#fi

export PAGER='less'
alias more=less

#
# Grep
#
alias grep=egrep

#
# Perlbrew
#
if [ -d $HOME/perl5/perlbrew ]
then
    source $HOME/perl5/perlbrew/etc/bashrc
fi
export PATH MANPATH INFOPATH

#
# Linuxbrew
#
LINUXBREW_HOME_ALT=/home/linuxbrew/.linuxbrew
LINUXBREW_HOME=/home/.linuxbrew
if [ -d $LINUXBREW_HOME ]
then
    path=($LINUXBREW_HOME/bin $path)
    manpath=($LINUXBREW_HOME/share/man $manpath)
    infopath=($LINUXBREW_HOME/share/info $infopath)
elif [ -d $LINUXBREW_HOME_ALT ]
then
    LINUXBREW_HOME=$LINUXBREW_HOME_ALT
    path=($LINUXBREW_HOME/bin $path)
    manpath=($LINUXBREW_HOME/share/man $manpath)
    infopath=($LINUXBREW_HOME/share/info $infopath)
fi

export PATH MANPATH INFOPATH

 - `AUTO_CD` auto changes to a directory without typing `cd`.
  - `AUTO_PUSHD` pushes the old directory onto the stack on `cd`.
  - `PUSHD_IGNORE_DUPS` does not store duplicates in the stack.
  - `PUSHD_SILENT` does not print the directory stack after `pushd` or `popd`.
  - `PUSHD_TO_HOME` pushes to the home directory when no argument is given.
  - `CDABLE_VARS` changes directory to a path stored in a variable.
  - `AUTO_NAME_DIRS` auto adds variable-stored paths to `~` list.
  - `MULTIOS` writes to multiple descriptors.
  - `EXTENDED_GLOB` uses extended globbing syntax.
  - `CLOBBER` does not overwrite existing files with `>` and `>>`. Use `>!` and
    `>>!` to bypass.

#
# setopts
#

# If we have a glob this will expand it
setopt GLOB_COMPLETE

# 10 second wait if you do something that will delete everything.  I wish I'd had this before...
#setopt RM_STAR_WAIT

# use magic (this is default, but it can't hurt!)
setopt ZLE

setopt NO_HUP

# setopt IGNORE_EOF

# If I could disable Ctrl-s completely I would!
setopt NO_FLOW_CONTROL

# Case insensitive globbing
setopt NO_CASE_GLOB

# Be Reasonable!
setopt NUMERIC_GLOB_SORT

# hows about arrays be awesome?
# (that is, frew${cool}frew has frew surrounding all the variables, not just first and last
setopt RC_EXPAND_PARAM

alias ls="ls -F"

#[ -f /usr/local/etc/profile.d/autojump.sh ] && . /usr/local/etc/profile.d/autojump.sh

export LD_LIBRARAY_PATH CDPATH FPATH MAILPATH MANPATH INFOPATH PATH
