#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...

#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

fpath=($HOME/bin /usr/local/bin $fpath)

# Perlbrew stuff
source $HOME/perl5/perlbrew/etc/bashrc

# why would you type 'cd dir' if you could just type 'dir'?
setopt AUTO_CD

# Now we can pipe to multiple outputs!
# setopt MULTIOS

# This makes cd=pushd
setopt AUTO_PUSHD

# This will use named dirs when possible
setopt AUTO_NAME_DIRS

# If we have a glob this will expand it
# setopt GLOB_COMPLETE
# setopt PUSHD_MINUS

# No more annoying pushd messages...
setopt PUSHD_SILENT

# blank pushd goes to home
setopt PUSHD_TO_HOME

# this will ignore multiple directories for the stack.  Useful?  I dunno.
setopt PUSHD_IGNORE_DUPS

# 10 second wait if you do something that will delete everything.  I wish I'd had this before...
setopt RM_STAR_WAIT

# use magic (this is default, but it can't hurt!)
setopt ZLE

# setopt NO_HUP

# setopt IGNORE_EOF

# If I could disable Ctrl-s completely I would!
setopt NO_FLOW_CONTROL

# Keep echo "station" > station from clobbering station
setopt NO_CLOBBER

# Case insensitive globbing
# setopt NO_CASE_GLOB

# Be Reasonable!
# setopt NUMERIC_GLOB_SORT

# I don't know why I never set this before.
# setopt EXTENDED_GLOB

# hows about arrays be awesome?  (that is, frew${cool}frew has frew surrounding all the variables, not just first and last
# setopt RC_EXPAND_PARAM

# Who doesn't want home and end to work?
bindkey '\e[1~' beginning-of-line
bindkey '\e[4~' end-of-line

# Incremental search is elite!
bindkey -M vicmd "/" history-incremental-search-backward
bindkey -M vicmd "?" history-incremental-search-forward

# Search based on what you typed in already
bindkey -M vicmd "//" history-beginning-search-backward
bindkey -M vicmd "??" history-beginning-search-forward

bindkey "\eOP" run-help

# oh wow!  This is killer...  try it!
bindkey -M vicmd "q" push-line

# it's like, space AND completion.  Gnarlbot.
bindkey -M viins ' ' magic-space

# my customizations
# source ~/.zprezto/init.zsh

export VISUAL=$EDITOR
export LSCOLORS="exfxcxdxbxegedabagacad"

alias ls="ls -F"

export GIT_EDITOR="emacs"

# alias gs='git status '
# alias ga='git add '
# alias gap='git add -p' # patch mode
# alias gb='git branch '
# alias gc='git commit'
# alias gd='git diff'
# alias go='git checkout ' # need this for "go" compiles
# alias gh='git hist'
# alias gha='git hist --all'
# alias gp='git pull'
# alias gpgp='git pull && git push'

 export MARKPATH=$HOME/.dfaciane
 function jump {
   cd -P $MARKPATH/$1 2>/dev/null || echo "No such mark: $1"
 }
 function mark {
   mkdir -p $MARKPATH; ln -s $(pwd) $MARKPATH/$1
 }
 function unmark {
   rm -i $MARKPATH/$1
 }
 function marks {
   \ls -l $MARKPATH | tail -n +2 | sed 's/  / /g' | cut -d' ' -f9- | awk -F ' -> ' '{printf "%-10s -> %s\n", $1, $2}'
 }
 alias j="jump"
 alias m="mark"

# alias cppcompile='c++ -std=c++11 -stdlib=libc++'
# unalias rm


